#!/bin/bash
. /bin/envd-load

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

echo "Running confd with Service Directory: $SCRIPTPATH"
confd -config-file /etc/confd/confd.toml -confdir "$SCRIPTPATH"
echo "Confd quitted sleeping for a while"
sleep 600
